name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up AWS credentials using GitHub Secrets
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    # Sync the files to the S3 bucket
    - name: Deploy to S3
      run: aws s3 sync ./ s3://your-bucket-name --delete

    # Invalidate the CloudFront cache
    - name: Invalidate CloudFront Cache
      run: aws cloudfront create-invalidation --distribution-id E571O738KN97S --paths "/*"